### ISSUE TITLE
Cannot load pdb from URL

### ISSUE THREAD

**Issue by rocfo** [epam/miew#393] opened 2022-02-09 14:28 UTC
The viewer cannot open a pdb file from a URL.
I am using a URL that points directly to a file hosted on Zenodo:
https://zenodo.org/record/3857791/files/4ptv_apo.c0.pdb?download=1
If I download the file, then upload it to miew.app from my computer, it works as expected.

1. Go to miew.app
2. Click on Menu, Load
3. Paste the link https://zenodo.org/record/3857791/files/4ptv_apo.c0.pdb?download=1
4. Click on Load

**Expected behavior**
Load and display the pdb structure file.

**Screenshots**
![Screenshot_20220209_133346](https://user-images.githubusercontent.com/54138025/153202214-5e4d2892-7c5a-472c-97c5-dbdefd887ae4.png)

**Desktop:**
 - OS: Linux Fedora 28
 - Browser: chrome
 - Version  98.0.4758.80 (Official Build) (64-bit)

**Additional context**
The final goal is to obtain a URL to a specific visualization using Miew, with the structure file publicly accessible, so that the user does not need to download and upload the file. That would be fantastic!

**Comment by AnaMoskvina** [comment] 2022-02-09 15:36
Dear  @rocfo,

Thank you for your interest in Miew.

The issue you faced is caused by the [CORS ](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)policy of the resource you are using  (you can see the corresponding message in a browser's console): the server doesn't allow other domains to access data, and we cannot impact such behavior.

Feel free to contact us, if you have any questions, we will be happy to help.

Best regards,
Miew team

**Comment by rocfo** [comment] 2022-02-11 11:33
Dear @AnaMoskvina ,
thanks for looking into this. Good to know it's not a bug.
Do you know of any public data repository that allows other domains to access data?
Best,
Rocco

**Comment by AnaMoskvina** [comment] 2022-02-11 13:16
Dear @rocfo,

You can check out these resources:
- [RCSB Protein Data Bank ](https://www.rcsb.org/), example link you can pass as a link to load: https://files.rcsb.org/download/1aid.pdb or https://files.rcsb.org/view/1aid.pdb
- [PubChem](https://pubchem.ncbi.nlm.nih.gov/), example link: https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/aspirin/JSON?record_type=3d

Best regards,
Anastasiia

**Comment by paulsmirnov** [comment] 2022-07-30 21:11
I hope the question was successfully resolved. Closing.

**Closed by paulsmirnov** 2022-07-30 21:11 UTC
Labels: question
